version: '3.7'

services:
  frontend:
    image: node:16-alpine
    container_name: Brofolio
    ports: [3000:3000]
    working_dir: /app/frontend
    volumes:
      - ./:/app/frontend
    command: npm start
